-- Advance Business Analysis

-- Top 5 Products by Total Sales

SELECT TOP  5
	Item,
	SUM(Total_Spent) AS TotalSales
FROM retail_store_sales
GROUP BY Item
ORDER BY TotalSales DESC;

-- Category with the Highest Sales Contribution

SELECT TOP 1
	Category,
	ROUND(SUM(Total_Spent) / (SELECT SUM(Total_Spent) FROM retail_store_sales) * 100,2) AS Contribution
FROM retail_store_sales
GROUP BY Category
ORDER BY Contribution DESC;

-- Highest-Sales Mont for Each Year.

SELECT
	Year,
	Month,
	TotalSales
FROM (
	SELECT
		YEAR(Transaction_Date) AS Year,
		MONTH(Transaction_Date) AS Month,
		SUM(Total_Spent) AS TotalSales,
		ROW_NUMBER() OVER(PARTITION BY YEAR(Transaction_Date) ORDER BY SUM(Total_Spent) DESC) AS rn
	FROM retail_store_sales
	GROUP BY 
		YEAR(Transaction_Date),
		MONTH(Transaction_Date))t
WHERE rn = 1
ORDER BY Year DESC;

-- Rank Customers by Total Spending

SELECT
	Customer_ID,
	SUM(Total_Spent) AS TotalSpending,
	ROW_NUMBER() OVER(ORDER BY SUM(Total_Spent) DESC) AS rn
FROM retail_store_sales
GROUP BY Customer_ID;

-- Customers with More Than One Purchase

SELECT
	Customer_ID,
	COUNT(*) AS TotalOrders
FROM retail_store_sales
GROUP BY Customer_ID
HAVING COUNT(*) > 500;

-- High-Value Customers
-- Find customers whose total spending is greater than the average spending across all customers.

WITH CTE1 AS (
SELECT
	Customer_ID,
	SUM(Total_Spent) AS Total_Spent
FROM retail_store_sales
GROUP BY Customer_ID )

SELECT
*
FROM CTE1
WHERE Total_Spent > (SELECT AVG(Total_Spent) FROM CTE1)


-- Multi-Category Customers
-- Find customers who have purchased products from more than one category.

SELECT
	Customer_ID,
	COUNT(DISTINCT Category) AS Categories
FROM retail_store_sales
GROUP BY Customer_ID
HAVING COUNT(DISTINCT Category) > 1;

-- First and Last Purchase
-- For each customer, find the first purchase date and last purcase date.
SELECT
	Customer_ID,
	MIN(Transaction_Date) AS FirstPurchase,
	MAX(Transaction_Date) AS LastPurchase
FROM retail_store_sales
GROUP BY Customer_ID;

-- Customer Purchase Duration
-- For each customer, calculate the number of days between their first and last purchase.

SELECT
	Customer_ID,
	MIN(Transaction_Date) AS FirstPurchase,
	MAX(Transaction_Date) AS LastPurchase,
	DATEDIFF(DAY,MIN(Transaction_Date),MAX(Transaction_Date)) AS Days
FROM retail_store_sales
GROUP BY Customer_ID;

-- Most Frequent Customer
-- Find the top 5 customers with the highest number of transactions.

SELECT TOP 5
	Customer_ID,
	COUNT(*) AS TotalOrders
FROM retail_store_sales
GROUP BY Customer_ID
ORDER BY TotalOrders DESC;

-- Customer category loyalty
-- For each customer's most purchased category based on the number of trasactions.

SELECT
	Customer_ID,
	Category,
	TotalOrders
FROM (
	SELECT
		Customer_ID,
		Category,
		COUNT(*) AS TotalOrders,
		ROW_NUMBER() OVER(PARTITION BY Customer_ID ORDER BY COUNT(*) DESC) AS rn
	FROM retail_store_sales
	GROUP BY 
		Customer_ID,
		Category
	)s
WHERE rn = 1

-- Category sales ranking
-- Rank all categorie's by their total sales,from highest to lowest.

SELECT
	Category,
	SUM(Total_Spent) AS Sales,
	ROW_NUMBER() OVER(ORDER BY SUM(Total_Spent) DESC) AS CategoryRN
FROM retail_store_sales 
GROUP BY Category;

-- Customer contribution
-- Calculate each customer's percentage contribution to total sales.

SELECT
	Customer_ID,
	ROUND(SUM(Total_Spent) / (SELECT SUM(Total_Spent) FROM retail_store_sales) * 100,2) AS Contribution
FROM retail_store_sales 
GROUP BY Customer_ID;

-- Repeat customer sales
-- Calculate the total sales generated by customers who made more than one transaction.

SELECT
	Customer_ID,
	SUM(Total_Spent) AS TotalAmount
FROM retail_store_sales
GROUP BY Customer_ID
HAVING COUNT(*) > 1;

-- Monthly sales comparision
-- For each month, calculate the total sales and the previous month's sales.

SELECT
	YEAR(Transaction_Date) AS Year,
	MONTH(Transaction_Date) AS Month,
	SUM(Total_Spent) AS CurrentMonthSales,
	LAG(SUM(Total_Spent)) OVER(ORDER BY YEAR(Transaction_Date),MONTH(Transaction_Date)) AS PreviousMonthSales
FROM retail_store_sales
GROUP BY 
	YEAR(Transaction_Date),
	MONTH(Transaction_Date);

-- Top customers in each category
-- Find the customer who spent the most in each category.
SELECT
	Customer_ID,
	Category,
	Total_Spent
FROM (
	SELECT
		Customer_ID,
		Category,
		SUM(Total_Spent) AS Total_Spent,
		ROW_NUMBER() OVER(PARTITION BY Category ORDER BY SUM(Total_Spent) DESC) AS rn
	FROM retail_store_sales
	GROUP BY 
		Customer_ID,
		Category,
		Item )t
WHERE rn = 1

-- Category average transaction
/* For each category,calculate:
   Total sales
   Number of transactions
   Average transaction value */

SELECT
	Category,
	SUM(Total_Spent) AS TotalSales,
	COUNT(*) AS TotalTransactions,
	ROUND(AVG(Total_Spent),2) AS AverageTransactionValues
FROM retail_store_sales
GROUP BY Category;

-- Customer Recency
/* For each customer, calculate the number of days since their last purchase,
   using the latest transaction date in the dataset as the reference date. */
SELECT
	Customer_ID,
	DATEDIFF(DAY,LastPurchaseDate,ReferenceDate) AS DifferenceInDays
FROM (
	SELECT
		Customer_ID,
		MAX(Transaction_Date) AS LastPurchaseDate,
		(SELECT MAX(Transaction_Date) FROM retail_store_sales) AS ReferenceDate
	FROM retail_store_sales
	GROUP BY Customer_ID)S

 -- Month-Over-Month Growth
 /* For each month, calculate:
    Current month's sales
	Previous month's sales
	Month-over-month sales growth percentage */

SELECT
	*,
	ROUND((CurrentMonthSales-PreviousMonthSles)/PreviousMonthSles*100,2) AS Growth
FROM (
	SELECT
		YEAR(Transaction_Date) AS Year,
		MONTH(Transaction_Date) AS Month,
		SUM(Total_Spent) AS CurrentMonthSales,
		LAG(SUM(Total_Spent)) OVER(ORDER BY YEAR(Transaction_Date),MONTH(Transaction_Date)) AS PreviousMonthSles
	FROM retail_store_sales
	GROUP BY 
		YEAR(Transaction_Date),
		MONTH(Transaction_Date) )s

-- Top 3 products in each category
-- Find the top 3 products by total sales within each category

SELECT
	Category,
	Item,
	TotalSales
FROM (
	SELECT
		Category,
		Item,
		SUM(Total_Spent) AS TotalSales,
		ROW_NUMBER() OVER(PARTITION BY Category ORDER BY SUM(Total_Spent) DESC) AS rn
	FROM retail_store_sales
	GROUP BY 
		Category,
		Item)F
WHERE rn <= 3;




